ARG FROM_IMAGE=registry.gitlab.com/appf-anu/pyts2:latest
FROM $FROM_IMAGE

RUN apt update && apt install -y --no-install-recommends cron

COPY crontab /etc/crontabs/root

CMD ["crond", "-f", "-d", "8"]